# Generated by Django 5.1.3 on 2024-11-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('lbin', models.IntegerField(default=0, verbose_name='Lowest BIN')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.IntegerField(default=0, verbose_name='Price in gems')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('skin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.skin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('favorite_skins', models.ManyToManyField(blank=True, related_name='favorited_by', to='main.skin')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_item_type', to='contenttypes.contenttype')),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_item_type', to='contenttypes.contenttype')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skin')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='main.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('pricepaid', models.IntegerField(default=0)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'verbose_name': 'Owned Skin',
                'verbose_name_plural': 'Owned Skins',
                'unique_together': {('user', 'skin', 'applied')},
            },
        ),
    ]
