# Generated by Django 5.1.3 on 2024-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_item_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='seller_item_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
