# Generated by Django 5.1.3 on 2024-11-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0002_sale_buyer_item_id_sale_seller_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='buyer_item_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buyer_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller_item_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller_type',
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='main.user')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.sale')),
            ],
        ),
    ]
