# Generated by Django 5.1.3 on 2024-11-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sale_buyer_item_id_remove_sale_buyer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='skin',
        ),
    ]
