# Generated by Django 5.1.3 on 2024-11-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sale_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='screenshot',
            field=models.URLField(blank=True, null=True),
        ),
    ]
