# Generated by Django 5.1.3 on 2024-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sale_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
