# Generated by Django 5.1.3 on 2024-11-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_saleitem_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_buyer', to='main.user')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skin')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_seller', to='main.user')),
            ],
        ),
    ]
