# Generated by Django 5.1.3 on 2024-11-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item_name',
            new_name='item',
        ),
    ]
